name: ideal_store
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0
dependencies:
  forui: ^0.13.1
  flutter:
    sdk: flutter
  uuid: ^4.4.0
  colornames: ^0.2.0
  hive_flutter: ^1.1.0
  objectbox: ^4.1.0
  objectbox_generator: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  flutter_native_splash: ^2.4.5
  navigation_builder: ^0.0.4
  path_provider: ^2.1.5
  package_info_plus: ^8.3.1
  path: ^1.9.1
dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^3.1.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
  #   - assets/fonts/
