name: ideal_store
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.0
  file_picker: ^8.1.3
  google_fonts: ^6.2.1
  colornames: ^0.2.0
  path_provider: ^2.1.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.0
  states_rebuilder: ^6.4.0
  flutter_bloc:
  manager:
    path: ..//manager
  objectbox: ^4.0.3
  objectbox_generator: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  path: ^1.9.0
  flex_color_scheme: ^8.0.2
  shadcn_ui: ^0.16.3
dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  analyzer: ^6.4.1
  # flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
