// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'authentication/authentication.dart';
import 'categories/categories.dart';
import 'orders/order.dart';
import 'products/product.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 8091855882071671905),
      name: 'Product',
      lastPropertyId: const obx_int.IdUid(10, 4341654225439993738),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6382313794465563722),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1654231124462536953),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5030601851494308519),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2945975673058616038),
            name: 'model',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8779205425249026508),
            name: 'path',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 9201214401877343614),
            name: 'editing',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6910626450500128331),
            name: 'brandIndex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2106678581067937458),
            name: 'colorIndex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 4685073644749528017),
            name: 'stock',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4341654225439993738),
            name: 'price',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 5158992040693962107),
      name: 'User',
      lastPropertyId: const obx_int.IdUid(6, 8973137379076258382),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3687616292067985248),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5816812022827336791),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4147950116996064526),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8428267859498448322),
            name: 'password',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2035065824286115776),
            name: 'roleIndex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8973137379076258382),
            name: 'cityIndex',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 9069988324371153085),
      name: 'Category',
      lastPropertyId: const obx_int.IdUid(2, 2364164196319984266),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5294511351316041737),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2364164196319984266),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 2690931117030937189),
      name: 'Order',
      lastPropertyId: const obx_int.IdUid(5, 3102584807158081327),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4698548115286762469),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1341206876999011901),
            name: 'editing',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1581989748259907097),
            name: 'statusIndex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 860676888920829078),
            name: 'createdOn',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3102584807158081327),
            name: 'customerId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 6951291558336331659),
            relationTarget: 'User')
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 5320381477935521909),
            name: 'products',
            targetId: const obx_int.IdUid(1, 8091855882071671905))
      ],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(7, 2690931117030937189),
      lastIndexId: const obx_int.IdUid(1, 6951291558336331659),
      lastRelationId: const obx_int.IdUid(1, 5320381477935521909),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [
        1336564712599621495,
        6331540883458232983,
        4642833903358294383
      ],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        2972244715611468810,
        1416314731801631373,
        6739371273187752418,
        1587781736321172294,
        6966317835554274912,
        604903400445658247,
        6374101978588626679,
        3848403668951896109,
        69788653585533327,
        2256481579363855267,
        5297743587549750354,
        8536948801261817010
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Product: obx_int.EntityDefinition<Product>(
        model: _entities[0],
        toOneRelations: (Product object) => [],
        toManyRelations: (Product object) => {},
        getId: (Product object) => object.id,
        setId: (Product object, int id) {
          object.id = id;
        },
        objectToFB: (Product object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final descriptionOffset = fbb.writeString(object.description);
          final modelOffset = fbb.writeString(object.model);
          final pathOffset =
              object.path == null ? null : fbb.writeString(object.path!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addOffset(3, modelOffset);
          fbb.addOffset(4, pathOffset);
          fbb.addBool(5, object.editing);
          fbb.addInt64(6, object.brandIndex);
          fbb.addInt64(7, object.colorIndex);
          fbb.addInt64(8, object.stock);
          fbb.addInt64(9, object.price);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Product()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..description = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..model = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..path = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 12)
            ..editing =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false)
            ..brandIndex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0)
            ..colorIndex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0)
            ..stock =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0)
            ..price =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);

          return object;
        }),
    User: obx_int.EntityDefinition<User>(
        model: _entities[1],
        toOneRelations: (User object) => [],
        toManyRelations: (User object) => {},
        getId: (User object) => object.id,
        setId: (User object, int id) {
          object.id = id;
        },
        objectToFB: (User object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final emailOffset = fbb.writeString(object.email);
          final passwordOffset = fbb.writeString(object.password);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, emailOffset);
          fbb.addOffset(3, passwordOffset);
          fbb.addInt64(4, object.roleIndex);
          fbb.addInt64(5, object.cityIndex);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = User()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..email = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..password = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..roleIndex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)
            ..cityIndex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);

          return object;
        }),
    Category: obx_int.EntityDefinition<Category>(
        model: _entities[2],
        toOneRelations: (Category object) => [],
        toManyRelations: (Category object) => {},
        getId: (Category object) => object.id,
        setId: (Category object, int id) {
          object.id = id;
        },
        objectToFB: (Category object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Category()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '');

          return object;
        }),
    Order: obx_int.EntityDefinition<Order>(
        model: _entities[3],
        toOneRelations: (Order object) => [object.customer],
        toManyRelations: (Order object) =>
            {obx_int.RelInfo<Order>.toMany(1, object.id): object.products},
        getId: (Order object) => object.id,
        setId: (Order object, int id) {
          object.id = id;
        },
        objectToFB: (Order object, fb.Builder fbb) {
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addBool(1, object.editing);
          fbb.addInt64(2, object.statusIndex);
          fbb.addInt64(3, object.createdOn.millisecondsSinceEpoch);
          fbb.addInt64(4, object.customer.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Order()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..editing =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false)
            ..statusIndex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
            ..createdOn = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          object.customer.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.customer.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<Order>(object.products, store,
              obx_int.RelInfo<Order>.toMany(1, object.id));
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Product] entity fields to define ObjectBox queries.
class Product_ {
  /// See [Product.id].
  static final id =
      obx.QueryIntegerProperty<Product>(_entities[0].properties[0]);

  /// See [Product.name].
  static final name =
      obx.QueryStringProperty<Product>(_entities[0].properties[1]);

  /// See [Product.description].
  static final description =
      obx.QueryStringProperty<Product>(_entities[0].properties[2]);

  /// See [Product.model].
  static final model =
      obx.QueryStringProperty<Product>(_entities[0].properties[3]);

  /// See [Product.path].
  static final path =
      obx.QueryStringProperty<Product>(_entities[0].properties[4]);

  /// See [Product.editing].
  static final editing =
      obx.QueryBooleanProperty<Product>(_entities[0].properties[5]);

  /// See [Product.brandIndex].
  static final brandIndex =
      obx.QueryIntegerProperty<Product>(_entities[0].properties[6]);

  /// See [Product.colorIndex].
  static final colorIndex =
      obx.QueryIntegerProperty<Product>(_entities[0].properties[7]);

  /// See [Product.stock].
  static final stock =
      obx.QueryIntegerProperty<Product>(_entities[0].properties[8]);

  /// See [Product.price].
  static final price =
      obx.QueryIntegerProperty<Product>(_entities[0].properties[9]);
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.id].
  static final id = obx.QueryIntegerProperty<User>(_entities[1].properties[0]);

  /// See [User.name].
  static final name = obx.QueryStringProperty<User>(_entities[1].properties[1]);

  /// See [User.email].
  static final email =
      obx.QueryStringProperty<User>(_entities[1].properties[2]);

  /// See [User.password].
  static final password =
      obx.QueryStringProperty<User>(_entities[1].properties[3]);

  /// See [User.roleIndex].
  static final roleIndex =
      obx.QueryIntegerProperty<User>(_entities[1].properties[4]);

  /// See [User.cityIndex].
  static final cityIndex =
      obx.QueryIntegerProperty<User>(_entities[1].properties[5]);
}

/// [Category] entity fields to define ObjectBox queries.
class Category_ {
  /// See [Category.id].
  static final id =
      obx.QueryIntegerProperty<Category>(_entities[2].properties[0]);

  /// See [Category.name].
  static final name =
      obx.QueryStringProperty<Category>(_entities[2].properties[1]);
}

/// [Order] entity fields to define ObjectBox queries.
class Order_ {
  /// See [Order.id].
  static final id = obx.QueryIntegerProperty<Order>(_entities[3].properties[0]);

  /// See [Order.editing].
  static final editing =
      obx.QueryBooleanProperty<Order>(_entities[3].properties[1]);

  /// See [Order.statusIndex].
  static final statusIndex =
      obx.QueryIntegerProperty<Order>(_entities[3].properties[2]);

  /// See [Order.createdOn].
  static final createdOn =
      obx.QueryDateProperty<Order>(_entities[3].properties[3]);

  /// See [Order.customer].
  static final customer =
      obx.QueryRelationToOne<Order, User>(_entities[3].properties[4]);

  /// see [Order.products]
  static final products =
      obx.QueryRelationToMany<Order, Product>(_entities[3].relations[0]);
}
